version: '3.8'
services:
  n8n:
    image: n8nio/n8n:0.146.0
    container_name: n8n
    depends_on:
      - mysql
    environment:
      N8N_PORT: ${N8N_PORT}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_PERSONALIZATION_ENABLED: ${N8N_PERSONALIZATION_ENABLED:-false}
      DB_TYPE: 'mysqldb'
      DB_MYSQLDB_DATABASE: ${DB_DATABASE}
      DB_MYSQLDB_HOST: ${DB_HOST}
      DB_MYSQLDB_PORT: ${DB_PORT}
      DB_MYSQLDB_USER: ${DB_USERNAME}
      DB_MYSQLDB_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${N8N_PORT}:${N8N_PORT}
  mysql:
    image: mysql:8.0.27
    ports:
      - ${DB_PORT}:3306
    restart: 'on-failure'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}


